# Setup
title:               A practical toolkit for mixed models in R
tagline:             'USDA ARS stats workshop'
description:         'A practical toolkit for mixed models in R: USDA ARS stats workshop: December 8-9, 2022.'
url:                 https://qdread.github.io
baseurl:             /glmm-workshop-dec2022
#paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Quentin Read
  url:               https://quentinread.com
  email:             quentin.read@usda.gov

# Gems
#plugins:
#  - insert here. None at the moment.

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y

github:
  repo:              https://github.com/qdread/glmm-workshop-dec2022
  
exclude:
  - .Rproj.user/
  - testing/
  - lessons/datasets
  - lessons/old_drafts/
  